import { useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, ShieldCheck } from 'lucide-react';
import { emptyData, persistenceIssue, validData, type AppData } from './model';
export default function Recovery({onRecover}:{onRecover:(data:AppData)=>Promise<void>|void}) {
  const file=useRef<HTMLInputElement>(null);const [confirm,setConfirm]=useState(false);const [error,setError]=useState('');const restoringRef=useRef(false);const [restoring,setRestoring]=useState(false);
  const restore=async(data:AppData)=>{if(restoringRef.current)return;restoringRef.current=true;setRestoring(true);setError('');try{await onRecover(data);}catch(err){setError(err instanceof Error?err.message:'恢复失败，原始记录仍然保留。');}finally{restoringRef.current=false;setRestoring(false);}};
  const download=()=>{const url=URL.createObjectURL(new Blob([persistenceIssue?.raw||''],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='栖时-原始记录备份.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="recovery-title"><header><h2 id="recovery-title">先保护你的记录</h2><ShieldCheck size={25}/></header><p style={{fontSize:13,lineHeight:1.9,color:'#7e896f'}}>现有记录暂时无法读取。原始数据仍然保留，自动保存已暂停；你可以先下载原始记录，或从已有备份恢复。</p><p className="form-error">{persistenceIssue?.message}</p><div style={{display:'flex',gap:9,marginTop:20,flexWrap:'wrap'}}><button className="btn btn-soft" disabled={persistenceIssue?.raw===null} onClick={download}><ArrowDownToLine size={15}/> 下载原始记录</button><button className="btn btn-primary" disabled={restoring} onClick={()=>file.current?.click()}><ArrowUpFromLine size={15}/> {restoring?'正在恢复…':'选择备份恢复'}</button></div><input hidden disabled={restoring} ref={file} type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>10*1024*1024)throw Error('备份文件不能超过 10 MB');const d:unknown=JSON.parse(await f.text());if(!validData(d))throw Error('文件格式无效，请选择栖时导出的备份');await restore(d);}catch(err){setError(err instanceof Error?err.message:'恢复失败');}}}/>{error&&<p className="form-error" role="alert">{error}</p>}<footer><button className="btn" disabled={restoring} onClick={()=>setConfirm(true)}>使用空白空间重新开始</button></footer>{confirm&&<div className="import-confirm"><strong>这将替换原有记录，请先下载原始备份。</strong><div style={{marginTop:12}}><button className="btn btn-soft" disabled={restoring} onClick={()=>setConfirm(false)}>取消</button><button className="btn btn-primary" disabled={restoring} onClick={()=>void restore(emptyData())}>{restoring?'正在恢复…':'确认重新开始'}</button></div></div>}</section></div>;
}
